import {
  Atom,
  Bed,
  BookMarked,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Car,
  Circle,
  Clapperboard,
  Cpu,
  Droplets,
  Dumbbell,
  Film,
  Gamepad2,
  Hammer,
  House,
  Languages,
  Library,
  type LucideIcon,
  MoonStar,
  Music,
  Newspaper,
  NotebookPen,
  PenLine,
  Shield,
  ShieldAlert,
  ShoppingBag,
  Sigma,
  Smartphone,
  Sunrise,
  Target,
  Tv,
  Users,
  Utensils,
  VolumeX,
} from "lucide-react";

// Only the icons categories and habits use, so the bundle does not carry all of lucide.
const MAP: Record<string, LucideIcon> = {
  atom: Atom,
  bed: Bed,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  bot: Bot,
  brain: Brain,
  briefcase: Briefcase,
  car: Car,
  clapperboard: Clapperboard,
  cpu: Cpu,
  droplets: Droplets,
  dumbbell: Dumbbell,
  film: Film,
  "gamepad-2": Gamepad2,
  hammer: Hammer,
  house: House,
  languages: Languages,
  library: Library,
  "moon-star": MoonStar,
  music: Music,
  newspaper: Newspaper,
  "notebook-pen": NotebookPen,
  "pen-line": PenLine,
  shield: Shield,
  "shield-alert": ShieldAlert,
  "shopping-bag": ShoppingBag,
  sigma: Sigma,
  smartphone: Smartphone,
  sunrise: Sunrise,
  target: Target,
  tv: Tv,
  users: Users,
  utensils: Utensils,
  "volume-x": VolumeX,
};

export const ICON_NAMES = Object.keys(MAP);

export function NamedIcon({ name, className, size = 16 }: { name: string | null | undefined; className?: string; size?: number }) {
  const Icon = (name && MAP[name]) || Circle;
  return <Icon className={className} size={size} aria-hidden />;
}
