"""file sync, life events, api tokens, day reviews

Revision ID: c16a0aa9dae3
Revises: 524eb5259662
Create Date: 2026-10-03 02:18:14.680265
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'c16a0aa9dae3'
down_revision: str | None = '524eb5259662'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('day_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'review_date')
    )
    with op.batch_alter_table('day_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_reviews_user_id'), ['user_id'], unique=False)

    op.create_table('life_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('precision', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('area', sa.String(length=20), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('life_events', schema=None) as batch_op:
        batch_op.create_index('ix_life_events_user_date', ['user_id', 'event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('sync_state', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('conflict_body', sa.Text(), nullable=True))

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_state', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('conflict_body', sa.Text(), nullable=True))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefs', sa.JSON(), nullable=True))

    with op.batch_alter_table('watch_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('seconds', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watch_events', schema=None) as batch_op:
        batch_op.drop_column('seconds')
        batch_op.drop_column('ended_at')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('prefs')

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_column('conflict_body')
        batch_op.drop_column('sync_state')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_column('conflict_body')
        batch_op.drop_column('sync_state')
        batch_op.drop_column('file_path')

    with op.batch_alter_table('life_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_events_user_id'))
        batch_op.drop_index('ix_life_events_user_date')

    op.drop_table('life_events')
    with op.batch_alter_table('day_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_reviews_user_id'))

    op.drop_table('day_reviews')
    with op.batch_alter_table('api_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_tokens_token_hash'))

    op.drop_table('api_tokens')
    # ### end Alembic commands ###
